<?php
/**
 * Taxjar_SalesTax
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Taxjar
 * @package    Taxjar_SalesTax
 * @copyright  Copyright (c) 2017 TaxJar. TaxJar is a trademark of TPS Unlimited, Inc. (http://www.taxjar.com)
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>
<div class="entry-edit">
    <?php echo $this->getFormHtml() ?>
</div>
<?php echo $this->getChildHtml('form_after'); ?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4>Output Log</h4>
    </div>
    <div class="fieldset">
        <div class="hor-scroll">
            <div id="transaction-sync-log" style="overflow: auto; max-height: 500px; margin-bottom: 1em">
                <pre style="overflow: visible">Awaiting sync! Click "Sync to TaxJar" to start syncing transactions.</pre>
            </div>
        </div>
    </div>
</div>
<script>
    function syncTransactions() {
        var syncAction = $('backfill_form').action;
        var syncButton = $('transaction-sync-button');
        var syncLog = $('transaction-sync-log');

        syncButton.disabled = true;
        syncButton.select('span').last().update('Syncing...');

        new Ajax.Request(syncAction, {
            method: 'get',
            parameters: {
                from_date: $('from').value,
                to_date: $('to').value
            },
            onCreate: function(request) {
                varienLoaderHandler.handler.onCreate({options: {loaderArea: true}});
            },
            onComplete: function(response) {
                var data = response.responseJSON;

                varienLoaderHandler.handler.onComplete();

                if (data.result) {
                    syncLog.select('pre').first().update('');

                    data.result.forEach(function(line) {
                        syncLog.select('pre').first().insert(line);
                    });
                } else {
                    syncLog.select('pre').first().update('Error: ' + data.error_message);
                }

                syncButton.disabled = false;
                syncButton.select('span').last().update('Sync to TaxJar');
            }
        });
    }
</script>
